### ISSUE TITLE
Navigator component

### ISSUE THREAD

**Issue by dangreen** [TrigenSoftware/weather#27]
Currently we have navigation like this: https://github.com/TrigenSoftware/weather/blob/master/src/App/App.tsx#L27-L43

We need move this to component, usage of this component should look like this:
```tsx
<Navigator>
    <Link to='/'>
        Home
    </Link>
    <Link to='/weather'>
        Weather
    </Link>
    <Link to='/todo'>
        Todo
    </Link>
</Navigator>
```

`<Navigator>` should based on `Menu` component:
https://trigensoftware.github.io/flexis-ui/?selectedKind=Menu&selectedStory=with%20items&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs
(click on `Show Info` button)

Working branch: `components/Navigator`

**Comment by Rustamhabibullin** [comment]
@dangreen

**Comment by Rustamhabibullin** [comment]
@dangreen Поправил, посмотри пожалуйста

**Comment by Rustamhabibullin** [comment]
@dangreen внес правки

**Comment by Rustamhabibullin** [comment]
@dangreen поправил проверку

**Comment by dangreen** [comment]
Done in #34
