### ISSUE TITLE
Fix working with `children`

### ISSUE THREAD

**Issue by dangreen** [TrigenSoftware/weather#35]
1) Filter with `child && (...)` instead `.filter(Boolean)`
2) Use `Children.map`, no any `Children.toArray(...).filter(...).map(...)` and etc.

Working branch: `children-map-mod`

**Comment by Rustamhabibullin** [comment]
@dangreen  не совсем понял что именно делать, т.е я в проекте weather должен найти везде где используется .filter(Boolean) Children.toArray(...).filter(...).map(...) и переделать примерно так же как это было в компоненте Navigator? 

В компоненте TodoList есть конструкция
{Children
					.toArray(children)
					.filter(Boolean)
					.map((child: ReactElement<any>) => cloneElement(child, {
						onSubmit: this.onChange,
						onDelete: this.onDelete
					}))
				} 
ее нужно переделать?

**Comment by dangreen** [comment]
@Rustamhabibullin 

> и переделать примерно так же как это было в компоненте Navigator

да

**Comment by dangreen** [comment]
Done in #37
